coverage:
  precision: 2
  round: down
  range: 80..100
  status:
    project:
      default:
        target: 80%
        threshold: 2%
    patch:
      default:
        target: 80%

comment:
  layout: reach,diff,flags,files
  require_changes: true

github_checks:
  annotations: true
